### ISSUE TITLE
mutations

### ISSUE THREAD

**Issue by ricksmit3000** [saihaj/sangat-library#1]
Hi there! just wanted to say that this is a great example for using `graphql-relay` and helped me a lot! I was just wondering how you'd handle mutations? I see there's a `TypeName` for Mutations, but couldn't find an example for that.

I tried to muck about with `mutationWithClientMutationId` but I noticed I can't really type the context in `mutateAndGetPayload` and I thought there might be a better way to define mutations than I'm currently doing.

**Comment by saihaj** [comment]
Good to hear you found this useful (still unfinished like many other side projects : )). Yeah I haven't written a mutation for it yet. 

> I tried to muck about with mutationWithClientMutationId but I noticed I can't really type the context in mutateAndGetPayload 

The way `mutationWithClientMutationId` has its types make it tricky https://github.com/graphql/graphql-relay-js/blob/5f0076227fb23b6eff8b4e981318f19315ce8c26/src/mutation/mutation.d.ts#L40-L42 to types as a generic like we do for `GraphQLFieldConfigMap`.  

Since `mutateAndGetPayload` is of `mutationFn` type https://github.com/graphql/graphql-relay-js/blob/5f0076227fb23b6eff8b4e981318f19315ce8c26/src/mutation/mutation.d.ts#L10 on way to type in arguments is: 
```ts
const mutationResolver = mutationWithClientMutationId({
  name: 'CreateLibrary',
  inputFields: {
    name: { type: GraphQLNonNull(GraphQLString) },
    address: { type: GraphQLNonNull(AddressType) },
    phone: { type: GraphQLNonNull(GraphQLPhoneNumber) },
    email: { type: GraphQLNonNull(GraphQLEmailAddress) },
  },
  outputFields: {
    library: {
      type: LibraryType,
    },
  },
  mutateAndGetPayload: async (args: Library, ctx: GraphQLContext) => {
    console.log(args)
  },
})
```

But I think a better api would be if we can pass a generic to `mutationWithClientMutationId<TSource, TContext>` just hacked it around types locally

```ts
type MutationFn<TContext> = (object: any, ctx: TContext, info: GraphQLResolveInfo) => unknown;

interface MutationConfig<TSource, TContext> {
  name: string;
  description?: string;
  deprecationReason?: string;
  extensions?: GraphQLFieldExtensions<TSource, TContext>;
  inputFields: Thunk<GraphQLInputFieldConfigMap>;
  outputFields: Thunk<GraphQLFieldConfigMap<TSource, TContext>>;
  mutateAndGetPayload: MutationFn<TContext>;
}

export function mutationWithClientMutationId<TSource, TContext>(
  config: MutationConfig<TSource,TContext>,
): GraphQLFieldConfig<TSource, TContext>;
``` 
 Now if we can provide generic and no need to type the args explicitly
![image](https://user-images.githubusercontent.com/44710980/141697950-d925b3d4-10cc-43ed-b404-cda0d63e0b43.png)

Edit: Exploring [Artsy's metaphysics](https://github.com/artsy/metaphysics#metaphysics) they have a patch that does a better job on typing this cause now you can even pass types for input args and use them https://github.com/artsy/metaphysics/blob/b394e0130017850ed1d2346338fab505c507e507/patches/%40types/graphql-relay%2B0.4.9.patch#L33-L64

**Comment by ricksmit3000** [comment]
Thank you so much for taking the time to write this, very kind and it helped me a lot! I noticed with the way `mutationWithClientMutationId` I had to type the arguments, but I like the generics approach much more!
